"""稳定错误码（对客户端可见的安全标识）。

约定：
- 错误码是稳定的字符串常量，客户端据此分支处理，不得携带异常细节；
- 面向用户的安全提示由调用方给出（safe_message），原始异常只进日志；
- 新增错误码只增不改，保证兼容性。
"""

MODEL_TIMEOUT = "MODEL_TIMEOUT"
MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
RETRIEVAL_FAILED = "RETRIEVAL_FAILED"
TOOL_UNAVAILABLE = "TOOL_UNAVAILABLE"
TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"
TOOL_ARGUMENT_INVALID = "TOOL_ARGUMENT_INVALID"
SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
INVALID_MODEL_OUTPUT = "INVALID_MODEL_OUTPUT"
STREAM_FAILED = "STREAM_FAILED"
CONTAINER_NOT_READY = "CONTAINER_NOT_READY"
INTERNAL_ERROR = "INTERNAL_ERROR"
